# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User: { algorithm: auto }

    providers:
        app_user_provider:
            entity: { class: App\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/auth
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /auth/login_check
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

    access_control:
        - { path: ^/auth, roles: PUBLIC_ACCESS }
        - {path: ^/, roles: IS_AUTHENTICATED_FULLY }
